name: reuse

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  reuse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install reuse
        run: pipx install reuse
      - name: Add licenses to files
        run: ./scripts/add_license.sh 